name: Nginx Preview Deployment

on:
  pull_request:
    branches: [main]

jobs:
  deploy:
    name: Deploy Preview App
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "14"

      - name: Install dependencies
        run: npm install

      - name: Build the app
        run: npm run build

      - name: Install SSHPass
        run: sudo apt-get install -y sshpass

      - name: Deploy to Nginx server
        env:
          SSH_PASSWORD: ${{ secrets.SSH_PASSWORD }}
          SSH_HOST: ${{ secrets.SSH_HOST }}
          SSH_USERNAME: ${{ secrets.SSH_USERNAME }}
        run: |
          # Define the deployment directory for the preview
          DEPLOY_DIR="/var/www/ifclca_previews"

          # Create the directory and copy files
          sshpass -p $SSH_PASSWORD ssh -o StrictHostKeyChecking=no ${SSH_USERNAME}@${SSH_HOST} "mkdir -p ${DEPLOY_DIR}"
          sshpass -p $SSH_PASSWORD scp -r ./build/* ${SSH_USERNAME}@${SSH_HOST}:${DEPLOY_DIR}/

      - name: Post a comment with the preview URL
        uses: actions/github-script@v7
        with:
          script: |
            const previewUrl = `https://ifclca.com/preview`;
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `🚀 The preview app was successfully deployed at ${previewUrl}.`
            })

      - name: Cleanup after PR merge/close
        if: github.event.action == 'closed'
        env:
          SSH_PASSWORD: ${{ secrets.SSH_PASSWORD }}
          SSH_HOST: ${{ secrets.SSH_HOST }}
          SSH_USERNAME: ${{ secrets.SSH_USERNAME }}
        run: |
          sshpass -p $SSH_PASSWORD ssh -o StrictHostKeyChecking=no ${SSH_USERNAME}@${SSH_HOST} "
          sudo rm -rf /var/www/ifclca_previews/*
          "
