name: Nginx Preview Deployment

on:
  pull_request:
    branches: [main]

jobs:
  deploy:
    name: Deploy Preview App
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "14"

      - name: Install dependencies
        run: npm install

      - name: Build the app
        run: npm run build

      - name: Install SSHPass
        run: sudo apt-get install -y sshpass

      - name: Deploy to Nginx server
        env:
          SSH_PASSWORD: ${{ secrets.SSH_PASSWORD }}
          SSH_HOST: ${{ secrets.SSH_HOST }}
          SSH_USERNAME: ${{ secrets.SSH_USERNAME }}
          PREVIEW_PATH: ${{ secrets.PREVIEW_PATH }}
        run: |
          # Define the deployment directory and subdomain for the PR preview
          PR_NUMBER=${{ github.event.pull_request.number }}
          DEPLOY_DIR="/var/www/${PREVIEW_PATH}/pr-${PR_NUMBER}"
          PREVIEW_URL="https://ifclca.com/${PREVIEW_PATH}/pr-${PR_NUMBER}"

          # Create the directory and copy files
          sshpass -p $SSH_PASSWORD ssh -o StrictHostKeyChecking=no ${SSH_USERNAME}@${SSH_HOST} "mkdir -p ${DEPLOY_DIR}"
          sshpass -p $SSH_PASSWORD scp -r ./build/* ${SSH_USERNAME}@${SSH_HOST}:${DEPLOY_DIR}/

          # Set up Nginx configuration
          sshpass -p $SSH_PASSWORD ssh -o StrictHostKeyChecking=no ${SSH_USERNAME}@${SSH_HOST} "
          echo '
          location /${PREVIEW_PATH}/pr-${PR_NUMBER}/ {
              root ${DEPLOY_DIR};
              index index.html;

              try_files \$uri /index.html;
          }
          ' | sudo tee /etc/nginx/sites-available/pr-${PR_NUMBER}
          sudo ln -s /etc/nginx/sites-available/pr-${PR_NUMBER} /etc/nginx/sites-enabled/
          sudo nginx -s reload
          "

      - name: Post a comment with the preview URL
        uses: actions/github-script@v7
        with:
          script: |
            const prNumber = context.issue.number;
            const previewUrl = `https://ifclca.com/${process.env.PREVIEW_PATH}/pr-${prNumber}`;
            github.rest.issues.createComment({
              issue_number: prNumber,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `🚀 The preview app was successfully deployed at ${previewUrl}.`
            })

      - name: Cleanup after PR merge/close
        if: github.event.action == 'closed'
        env:
          SSH_PASSWORD: ${{ secrets.SSH_PASSWORD }}
          SSH_HOST: ${{ secrets.SSH_HOST }}
          SSH_USERNAME: ${{ secrets.SSH_USERNAME }}
          PREVIEW_PATH: ${{ secrets.PREVIEW_PATH }}
        run: |
          PR_NUMBER=${{ github.event.pull_request.number }}
          sshpass -p $SSH_PASSWORD ssh -o StrictHostKeyChecking=no ${SSH_USERNAME}@${SSH_HOST} "
          sudo rm -rf /var/www/${PREVIEW_PATH}/pr-${PR_NUMBER}
          sudo rm /etc/nginx/sites-available/pr-${PR_NUMBER}
          sudo rm /etc/nginx/sites-enabled/pr-${PR_NUMBER}
          sudo nginx -s reload
          "
