name: Nginx Preview Deployment

on:
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy Preview App
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "14" # Ensure this matches your server environment

      - name: Install dependencies
        run: npm install

      # No build step needed if your app doesn't require one

      - name: Install SSHPass
        run: sudo apt-get install -y sshpass

      - name: Deploy to Nginx server
        env:
          SSH_PASSWORD: ${{ secrets.SSH_PASSWORD }}
          SSH_HOST: ${{ secrets.SSH_HOST }}
          SSH_USERNAME: ${{ secrets.SSH_USERNAME }}
          PREVIEW_DOMAIN: ${{ secrets.PREVIEW_DOMAIN }}
        run: |
          # Define the deployment directory
          DEPLOY_DIR="/var/www/${PREVIEW_DOMAIN}/pr-${{ github.event.pull_request.number }}"

          # Create the directory and copy files
          sshpass -p $SSH_PASSWORD ssh -o StrictHostKeyChecking=no ${SSH_USERNAME}@${SSH_HOST} "mkdir -p ${DEPLOY_DIR}"
          sshpass -p $SSH_PASSWORD scp -r * ${SSH_USERNAME}@${SSH_HOST}:${DEPLOY_DIR}/

          # Restart the app with PM2
          sshpass -p $SSH_PASSWORD ssh -o StrictHostKeyChecking=no ${SSH_USERNAME}@${SSH_HOST} "
            cd ${DEPLOY_DIR} &&
            pm2 startOrReload ecosystem.config.js --env production
          "

      - name: Post a comment with the preview URL
        uses: actions/github-script@v7
        with:
          script: |
            const prNumber = context.issue.number;
            const previewUrl = `https://ifclca.com/${process.env.PREVIEW_DOMAIN}/pr-${prNumber}`;
            github.rest.issues.createComment({
              issue_number: prNumber,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `🚀 The preview app was successfully deployed at ${previewUrl}.`
            })

      - name: Cleanup after PR merge/close
        if: github.event.action == 'closed'
        env:
          SSH_PASSWORD: ${{ secrets.SSH_PASSWORD }}
          SSH_HOST: ${{ secrets.SSH_HOST }}
          SSH_USERNAME: ${{ secrets.SSH_USERNAME }}
          PREVIEW_DOMAIN: ${{ secrets.PREVIEW_DOMAIN }}
        run: |
          PR_NUMBER=${{ github.event.pull_request.number }}
          sshpass -p $SSH_PASSWORD ssh -o StrictHostKeyChecking=no ${SSH_USERNAME}@${SSH_HOST} "
          sudo rm -rf /var/www/${PREVIEW_DOMAIN}/pr-${PR_NUMBER}
          sudo nginx -s reload
          "
